DROP TABLE IF EXISTS USERS, EMAILS, PETS;
CREATE TABLE EMAILS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255)
);

CREATE TABLE USERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    AGE INT,
    EMAIL_ID INT REFERENCES EMAILS(ID));

CREATE TABLE PETS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NICKNAME VARCHAR(255),
    USER_ID INT REFERENCES USERS(ID)
);